#ifndef LX_RANDOM_HPP_INCLUDED
#define LX_RANDOM_HPP_INCLUDED


/*
*	Copyright (C) 2016 Luxon Jean-Pierre
*	gumichan01.olympe.in
*
*	The LunatiX Engine is a SDL2-based game engine.
*	It can be used for open-source or commercial games thanks to the zlib/libpng license.
*
*   Luxon Jean-Pierre (Gumichan01)
*	luxon.jean.pierre@gmail.com
*/


/**
*	@file LX_Random.hpp
*	@brief The Random Number Generator library
*	@author Luxon Jean-Pierre(Gumichan01)
*	@version 0.7
*
*/


/**
*	@namespace LX_Random
*	@brief The Random Number Generator (RNG) module
*
*   This namespace describes LX_Random. This random number generator is based on
*   the Xorshift* generator, but has also a support of the standard C generator
*/
namespace LX_Random
{

void initRand(void);
uint64_t xorshiftRand(void);
int crand(void);


/**
*   @fn uint64_t xorshiftRand100(void)
*
*   Xorshift random value between 0 and 100
*
*   @return A random value generated by the Xorshift* RNG
*
*/
inline uint64_t xorshiftRand100(void)
{
    return LX_Random::xorshiftRand()%100;
}


/**
*   @fn inline int crand100(void)
*
*   C random value between 0 and 100
*
*   @return A random value generated by the standard C RNG
*
*/
inline int crand100(void)
{
    return LX_Random::crand()%100;
}

};

#endif // LX_RANDOM_HPP_INCLUDED

